
const lessons = window.LESSONS;
const $ = s => document.querySelector(s);
const app = $('#app');
const state = {lesson:null, tab:'flash', card:0, flipped:false, teacher:false, quizDir:'lb-en', quiz:null, review:null, listeningRate:1};
const KEY='sproochentestTrainerV1';
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{cards:{},listening:{},streak:0,lastDay:null}}catch{return{cards:{},listening:{},streak:0,lastDay:null}}}
let progress=load();
function save(){localStorage.setItem(KEY,JSON.stringify(progress));}
function touchStreak(){const d=new Date(), today=d.toISOString().slice(0,10); if(progress.lastDay===today)return; const y=new Date(d);y.setDate(d.getDate()-1); const yesterday=y.toISOString().slice(0,10); progress.streak=progress.lastDay===yesterday?(progress.streak||0)+1:1; progress.lastDay=today;save();}
touchStreak();
function esc(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
function cardStatus(id){return progress.cards[id]||'new'}
function lessonMastery(l){return Math.round(l.vocab.filter(v=>cardStatus(v.id)==='known').length/20*100)}
function listeningScore(l){return progress.listening[l.id]||0}
function overall(){const known=lessons.flatMap(l=>l.vocab).filter(v=>cardStatus(v.id)==='known').length; const listen=lessons.reduce((a,l)=>a+listeningScore(l),0); return Math.round(((known/400)*.7+(listen/80)*.3)*100)}
function levelClass(level){return level==='Beginner'?'Beginner':level==='Developing'?'Developing':'Exam Ready'}
function speak(text,rate=1){if(!('speechSynthesis' in window)||!('SpeechSynthesisUtterance' in window)){alert('Speech playback is not supported by this browser.');return;} speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text);u.lang='lb-LU';u.rate=rate; const voices=speechSynthesis.getVoices(); const exact=voices.find(v=>v.lang.toLowerCase()==='lb-lu'); const lb=voices.find(v=>v.lang.toLowerCase().startsWith('lb')); if(exact||lb)u.voice=exact||lb;speechSynthesis.speak(u)}
function home(){state.lesson=null;state.review=null;renderHome();window.scrollTo(0,0)}
function renderHome(){
 const known=lessons.flatMap(l=>l.vocab).filter(v=>cardStatus(v.id)==='known').length;
 const listen=lessons.reduce((a,l)=>a+listeningScore(l),0);
 app.innerHTML=`<section class="hero"><div class="panel"><div class="eyebrow">Daily Sproochentest practice</div><h1>Speak more. Freeze less.</h1><p>400 progressive vocabulary cards, 20 listening drills, speaking timers and teacher tools. Start anywhere, but the lessons become gradually harder.</p><div class="toolbar"><button class="btn" id="reviewBtn">Today's 20-card review</button><button class="btn ghost" id="resetBtn">Reset progress</button></div><div class="notice">Audio uses your browser/device voice system. The app requests a Luxembourgish <b>lb-LU</b> voice; if your device does not provide one, it may use the closest available voice.</div></div><div class="panel stats"><div class="stat"><b>${overall()}%</b><span>overall completion</span></div><div class="stat"><b>${known}/400</b><span>cards mastered</span></div><div class="stat"><b>${listen}/80</b><span>listening answers</span></div><div class="stat"><b>${progress.streak||1}</b><span>day streak</span></div></div></section>
 <div class="section-title"><div><div class="eyebrow">Course map</div><h2>20 progressive lessons</h2></div><span class="muted">20 words each</span></div><section class="lessons">${lessons.map(l=>`<button class="lesson-card" data-id="${l.id}"><span class="lesson-num">LESSON ${l.id}</span><h3>${esc(l.title)}</h3><span class="pill">${l.level}</span><div style="height:12px"></div><div class="progress"><i style="width:${lessonMastery(l)}%"></i></div><div class="lesson-meta"><span>${lessonMastery(l)}% vocab</span><span>${listeningScore(l)}/4 listening</span></div></button>`).join('')}</section>`;
 document.querySelectorAll('.lesson-card').forEach(b=>b.onclick=()=>openLesson(+b.dataset.id));
 $('#reviewBtn').onclick=startReview; $('#resetBtn').onclick=()=>{if(confirm('Reset all saved card and listening progress?')){localStorage.removeItem(KEY);progress=load();touchStreak();renderHome()}};
}
function openLesson(id,tab='flash'){state.lesson=lessons[id-1];state.tab=tab;state.card=0;state.flipped=false;state.quiz=null;renderLesson();window.scrollTo(0,0)}
function renderLesson(){const l=state.lesson; const m=lessonMastery(l); app.innerHTML=`<div class="crumb"><button id="backHome">← Dashboard</button><span>/</span><span>Lesson ${l.id}</span></div><section class="panel lesson-head"><div><div class="eyebrow">Lesson ${l.id} · ${l.level}</div><h1>${esc(l.title)}</h1><p class="muted">${esc(l.objective)}</p></div><div style="min-width:190px"><b>${m}% vocabulary mastery</b><div class="progress" style="margin-top:8px"><i style="width:${m}%"></i></div></div></section><nav class="tabs"><button class="tab ${state.tab==='flash'?'active':''}" data-tab="flash">Flashcards</button><button class="tab ${state.tab==='quiz'?'active':''}" data-tab="quiz">Quick quiz</button><button class="tab ${state.tab==='listen'?'active':''}" data-tab="listen">Listening</button><button class="tab ${state.tab==='speak'?'active':''}" data-tab="speak">Speaking</button>${state.teacher?'<button class="tab '+(state.tab==='teacher'?'active':'')+'" data-tab="teacher">Teacher notes</button>':''}</nav><section id="lessonBody"></section>`;
 $('#backHome').onclick=home; document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;state.card=0;state.flipped=false;state.quiz=null;renderLesson()}); renderTab();}
function renderTab(){if(state.tab==='flash')renderFlash(); if(state.tab==='quiz')renderQuiz(); if(state.tab==='listen')renderListen(); if(state.tab==='speak')renderSpeak(); if(state.tab==='teacher')renderTeacher();}
function activeDeck(){return state.review||state.lesson.vocab}
function renderFlash(){const deck=activeDeck(); const v=deck[state.card%deck.length]; const l=state.lesson; $('#lessonBody').innerHTML=`<div class="flash-wrap"><div><button class="flashcard" id="flashCard" aria-label="Flashcard. Press space or tap to reveal.">${state.flipped?`<div><div class="eyebrow">Meaning</div><div class="meaning">${esc(v.en)}</div><div style="margin-top:16px"><button class="btn ghost" id="speakWord">🔊 Hear Luxembourgish</button></div></div>`:`<div><div class="eyebrow">Luxembourgish</div><div class="term">${esc(v.lb)}</div></div>`}<div class="hint">Tap or press Space to ${state.flipped?'hide':'reveal'} · ${state.card+1}/${deck.length}</div></button><div class="card-controls"><button class="btn ghost" id="prevCard">← Previous</button><button class="btn ghost" id="nextCard">Next →</button><button class="btn ghost" id="shuffle">Shuffle</button><button class="btn warn" id="again">Study again</button><button class="btn good" id="known">Know it</button></div></div><aside class="panel card-side"><h3>Lesson progress</h3><div class="progress"><i style="width:${lessonMastery(l)}%"></i></div><p class="muted">${l.vocab.filter(x=>cardStatus(x.id)==='known').length} known · ${l.vocab.filter(x=>cardStatus(x.id)==='again').length} to review</p><div class="mini-list">${l.vocab.slice(0,8).map(x=>`<div class="mini-row"><span>${esc(x.lb)}</span><span>${cardStatus(x.id)==='known'?'✓':cardStatus(x.id)==='again'?'↺':'·'}</span></div>`).join('')}</div></aside></div>`;
 $('#flashCard').onclick=e=>{if(e.target.id==='speakWord')return; state.flipped=!state.flipped;renderFlash()}; const sw=$('#speakWord'); if(sw)sw.onclick=e=>{e.stopPropagation();speak(v.lb)}; $('#prevCard').onclick=()=>{state.card=(state.card-1+deck.length)%deck.length;state.flipped=false;renderFlash()}; $('#nextCard').onclick=()=>{state.card=(state.card+1)%deck.length;state.flipped=false;renderFlash()}; $('#shuffle').onclick=()=>{state.card=Math.floor(Math.random()*deck.length);state.flipped=false;renderFlash()}; $('#again').onclick=()=>mark(v,'again'); $('#known').onclick=()=>mark(v,'known');
}
function mark(v,status){progress.cards[v.id]=status;save();state.card=(state.card+1)%activeDeck().length;state.flipped=false;renderFlash()}
function newQuiz(){const l=state.lesson, answer=l.vocab[Math.floor(Math.random()*l.vocab.length)], pool=l.vocab.filter(x=>x.id!==answer.id).sort(()=>Math.random()-.5).slice(0,3); const opts=[answer,...pool].sort(()=>Math.random()-.5); state.quiz={answer,opts,done:false,chosen:null}}
function renderQuiz(){if(!state.quiz)newQuiz(); const q=state.quiz; const dir=state.quizDir; const prompt=dir==='lb-en'?q.answer.lb:q.answer.en; $('#lessonBody').innerHTML=`<div class="quiz-card"><div class="toolbar"><button class="btn ${dir==='lb-en'?'':'ghost'}" id="dir1">Lux → English</button><button class="btn ${dir==='en-lb'?'':'ghost'}" id="dir2">English → Lux</button></div><div class="quiz-q">${esc(prompt)}</div><div class="answers">${q.opts.map(o=>{let cls='answer';if(q.done&&o.id===q.answer.id)cls+=' correct';else if(q.done&&q.chosen===o.id)cls+=' wrong';return `<button class="${cls}" data-id="${o.id}">${esc(dir==='lb-en'?o.en:o.lb)}</button>`}).join('')}</div>${q.done?`<div class="toolbar"><strong>${q.chosen===q.answer.id?'Correct.':'Correct answer: '+esc(dir==='lb-en'?q.answer.en:q.answer.lb)}</strong><button class="btn" id="nextQ">Next question</button></div>`:''}</div>`;
 $('#dir1').onclick=()=>{state.quizDir='lb-en';state.quiz=null;renderQuiz()};$('#dir2').onclick=()=>{state.quizDir='en-lb';state.quiz=null;renderQuiz()};document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{if(q.done)return;q.chosen=b.dataset.id;q.done=true;renderQuiz()});const nq=$('#nextQ');if(nq)nq.onclick=()=>{state.quiz=null;renderQuiz()};}
let plays=0;
function renderListen(){const l=state.lesson, li=l.listening; $('#lessonBody').innerHTML=`<div class="listen-card"><div class="eyebrow">Listening drill</div><h2>${esc(l.title)}</h2><div class="toolbar"><button class="btn" id="playL">▶ Play</button><button class="btn ghost" id="pauseL">Pause / resume</button><button class="btn ghost" id="stopL">Stop</button><button class="btn ghost" id="slowL">Slow 0.82×</button><button class="btn ghost" id="normalL">Normal 1×</button></div><p class="muted">Listens this session: <b id="playCount">${plays}</b></p><details class="listen-text"><summary><b>Show transcript</b></summary><p>${esc(li.text)}</p></details><div id="listenQs">${li.questions.map((q,i)=>`<div class="qblock"><h4>${i+1}. ${esc(q[0])}</h4><div class="qopts">${q[1].map((o,j)=>`<button class="qopt" data-q="${i}" data-o="${j}">${esc(o)}</button>`).join('')}</div><div class="explain" id="ex${i}"></div></div>`).join('')}</div></div>`;
 $('#playL').onclick=()=>{plays++;$('#playCount').textContent=plays;speak(li.text,state.listeningRate)};$('#pauseL').onclick=()=>speechSynthesis.paused?speechSynthesis.resume():speechSynthesis.pause();$('#stopL').onclick=()=>speechSynthesis.cancel();$('#slowL').onclick=()=>{state.listeningRate=.82;speechSynthesis.cancel()};$('#normalL').onclick=()=>{state.listeningRate=1;speechSynthesis.cancel()};document.querySelectorAll('.qopt').forEach(b=>b.onclick=()=>checkListening(b));}
function checkListening(b){const qi=+b.dataset.q, oi=+b.dataset.o, q=state.lesson.listening.questions[qi]; const block=b.closest('.qblock'); block.querySelectorAll('.qopt').forEach((x,j)=>{x.disabled=true;if(j===q[2])x.classList.add('correct');else if(j===oi)x.classList.add('wrong')}); $('#ex'+qi).textContent=(oi===q[2]?'Correct. ':'Not quite. ')+q[3]; block.dataset.correct=oi===q[2]?'1':'0'; const current=[...document.querySelectorAll('.qblock')].filter(bl=>bl.dataset.correct==='1').length; progress.listening[state.lesson.id]=Math.max(listeningScore(state.lesson),current);save();}
let timerInt=null;
function renderSpeak(){clearInterval(timerInt);const l=state.lesson; $('#lessonBody').innerHTML=`<div class="speak-card"><div class="eyebrow">Speaking practice</div><h2>30 seconds to prepare · 2 minutes to speak</h2><div class="speak-grid">${l.speaking.map((p,i)=>`<div class="prompt"><b>Prompt ${i+1}</b><p>${esc(p)}</p><button class="btn ghost startTimer" data-i="${i}">Start timer</button></div>`).join('')}</div><div id="timerArea"></div><div class="section-title"><h3>Exam phrases</h3></div><div class="exam-phrases"><div class="phrase">Kënnt Dir dat widderhuelen?</div><div class="phrase">Kënnt Dir méi lues schwätzen?</div><div class="phrase">Ech hunn dat net ganz verstanen.</div><div class="phrase">Ech kann e Beispill ginn.</div></div></div>`;document.querySelectorAll('.startTimer').forEach(b=>b.onclick=()=>startSpeakingTimer(+b.dataset.i));}
function startSpeakingTimer(i){clearInterval(timerInt);let phase='Prepare',s=30; const area=$('#timerArea'); const draw=()=>area.innerHTML=`<div class="panel" style="margin-top:16px;text-align:center"><div class="eyebrow">${phase}</div><p>${esc(state.lesson.speaking[i])}</p><div class="timer">${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}</div><button class="btn ghost" id="cancelTimer">Stop</button></div>`;draw(); timerInt=setInterval(()=>{s--;if(s<0&&phase==='Prepare'){phase='Speak';s=120;speak('Elo schwätzen.',1);draw();return}if(s<0){clearInterval(timerInt);phase='Finished';s=0;speak('Fäerdeg.',1)}draw();const c=$('#cancelTimer');if(c)c.onclick=()=>{clearInterval(timerInt);area.innerHTML=''}},1000);}
function renderTeacher(){const l=state.lesson; $('#lessonBody').innerHTML=`<div class="teacher-panel"><div class="eyebrow">Teacher view</div><h2>Lesson ${l.id}: ${esc(l.title)}</h2><p><b>Objective:</b> ${esc(l.objective)}</p><div class="toolbar"><button class="btn ghost" id="printLesson">Print lesson summary</button></div><h3>Vocabulary</h3><table><thead><tr><th>#</th><th>Luxembourgish</th><th>English</th></tr></thead><tbody>${l.vocab.map((v,i)=>`<tr><td>${i+1}</td><td>${esc(v.lb)}</td><td>${esc(v.en)}</td></tr>`).join('')}</tbody></table><h3>Listening transcript</h3><p>${esc(l.listening.text)}</p><h3>Question key</h3><ol>${l.listening.questions.map(q=>`<li><b>${esc(q[0])}</b> — ${esc(q[1][q[2]])}<br><span class="muted">${esc(q[3])}</span></li>`).join('')}</ol><h3>Follow-up conversation questions</h3><ul>${l.followups.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`;$('#printLesson').onclick=()=>window.print()}
function startReview(){let again=lessons.flatMap(l=>l.vocab).filter(v=>cardStatus(v.id)==='again');let rest=lessons.flatMap(l=>l.vocab).filter(v=>!again.some(a=>a.id===v.id)).sort(()=>Math.random()-.5);state.review=[...again.sort(()=>Math.random()-.5),...rest].slice(0,20);state.lesson=lessons[Math.max(0,Math.min(19,Math.floor(Math.random()*20)))];state.tab='flash';state.card=0;state.flipped=false;renderReviewShell()}
function renderReviewShell(){app.innerHTML=`<div class="crumb"><button id="backHome">← Dashboard</button><span>/</span><span>Today's review</span></div><section class="panel"><div class="eyebrow">Adaptive review</div><h1>Today's 20 cards</h1><p class="muted">Cards marked “Study again” are shown first, followed by a mixed review from the course.</p></section><section id="lessonBody" style="margin-top:18px"></section>`;$('#backHome').onclick=()=>{state.review=null;home()};renderFlash()}
function setupSearch(){const d=$('#searchDialog'),input=$('#searchInput'),res=$('#searchResults');$('#searchBtn').onclick=()=>{d.showModal();input.value='';input.focus();showHits('')};input.oninput=()=>showHits(input.value);function showHits(q){q=q.trim().toLowerCase();const hits=lessons.flatMap(l=>l.vocab.map(v=>({...v,lesson:l.id,title:l.title}))).filter(v=>!q||v.lb.toLowerCase().includes(q)||v.en.toLowerCase().includes(q)).slice(0,80);res.innerHTML=hits.map(v=>`<button class="search-hit" data-lesson="${v.lesson}"><b>${esc(v.lb)}</b><span>${esc(v.en)}</span><small>Lesson ${v.lesson}</small></button>`).join('')||'<p class="muted">No matches.</p>';res.querySelectorAll('.search-hit').forEach(b=>b.onclick=()=>{d.close();openLesson(+b.dataset.lesson,'flash')})}}
$('#teacherToggle').onchange=e=>{state.teacher=e.target.checked;if(state.lesson&&!state.review)renderLesson()};document.querySelector('[data-action="home"]').onclick=home;document.addEventListener('keydown',e=>{if(e.code==='Space'&&state.lesson&&state.tab==='flash'&&!['INPUT','TEXTAREA','BUTTON'].includes(document.activeElement.tagName)){e.preventDefault();state.flipped=!state.flipped;renderFlash()}});setupSearch();renderHome();
